CREATE TABLE cards (
    id BIGINT NOT NULL AUTO_INCREMENT,
    card_number VARCHAR(32) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    balance DECIMAL(19, 2) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    CONSTRAINT pk_cards PRIMARY KEY (id),
    CONSTRAINT uk_cards_card_number UNIQUE (card_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
